apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ${SERVICE_PREFIX_TO_REPLACE}-performance-default-deny-ingress
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
    - Ingress
