openapi: 3.0.0
info:
  title: Travel Time time filter fast API
  description: Json road distance API to return distance in meters from a given origin point to multiple destination points
  version: 0.0.1

paths:
  /road-distance:
    post:
      summary: Point-to-point road distance calculation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - locations
                - departure_searches
              properties:
                locations:
                  type: array
                  description: List of point locations
                  minItems: 1
                  maxItems: 2000
                  items:
                    type: object
                    required:
                      - id
                      - coords
                    properties:
                      id:
                        type: string
                        description: Unique reference to identify item in response
                      coords:
                        type: object
                        properties:
                          latitude:
                            type: number
                            description: Latitude point of origin
                          longitude:
                            type: number
                            description: Longitude point of origin
                        required:
                          - latitude
                          - longitude
                departure_searches:
                  type: array
                  description: orgin and destination configuration
                  items:
                    type: object
                    required:
                      - id
                      - departure_location_id
                      - arrival_location_ids
                      - transportation
                      - departure_time
                      - properties
                      - travel_time
                    properties:
                      id:
                        type: string
                        description: Name of request
                      departure_location_id:
                        type: string
                        description: Id from the locations array that identifies the origin location
                      arrival_location_ids:
                        type: array
                        description: Array of ids from the locations array that identify one or more destination locations
                        minItems: 1
                        maxItems: 2000
                        items:
                          type: string
                      transportation:
                        type: object
                        description: Details transportation method
                        properties:
                          type:
                            type: string
                            description: Type of transport - limited to 'driving'
                            enum: [driving]
                          parking_time:
                            type: integer
                            enum: [0]
                            description: Time in minutes to account for parking - limited to 0
                      arrival_time_period:
                        type: string
                        enum: [weekday_morning]
                        description: Date and time string representing the departure time in extended ISO-8601 format
                      properties:
                        type: array
                        description: Data attributes to return - limited to 'distance'
                        minItems: 1
                        maxItems: 1
                        items:
                          type: string
                          enum: [distance]
                      travel_time:
                        type: integer
                        minItems: 60
                        maxItems: 7200
                        description: Maximum time in seconds to reach destinations. Locations deemed a further travel time than this are return as unreachable
              example:
                locations:
                  - id: "1001"
                    coords:
                      latitude: 50.72179229048227
                      longitude: -3.525942582444856
                  - id: "1002"
                    coords:
                      latitude: 50.72179229048227
                      longitude: -3.525942582444856
                departure_searches:
                  - id: "description of search"
                    departure_location_id: "1001"
                    arrival_location_ids:
                      - "1002"
                    transportation:
                      - type: "driving"
                        parking_time: 0
                    arrival_time_period: "weekday_morning"
                    properties:
                      - "distance"
                    travel_time: 7200
      responses:
        200:
          description: The request was received successfully
          content:
            application/json:
              schema:
                type: object
                required:
                  - results
                properties:
                  results:
                    type: object
                    required:
                      - search_id
                    description: Results wrapper
                    properties:
                      search_id:
                        type: string
                        description: The id specified for departure_searches in the request
                      locations:
                        type: array
                        minItems: 1
                        maxItems: 2000
                        items:
                          type: object
                          description: Details for each returned locations
                          required:
                            - id
                            - properties
                          properties:
                            id:
                              type: string
                              description: The id provided in the request for the given location
                            properties:
                              type: array
                              description: A list of any data attributes requested in departure_searches.properties
                              minItems: 1
                              maxItems: 1
                              items:
                                type: object
                                description: Requested data attributes
                                required:
                                  - distance
                                properties:
                                  distance:
                                    type: integer
                                    description: Distance from destination to this location in meters
                  unreachable:
                    type: array
                    maxItems: 2000
                    items:
                      type: string
                      description: Id of the location that has been deemed too distance to reach within travel_time
        500:
          description: We are having issues with our servers right now. Please contact us if you keep seeing this to help resolve the issue
          content:
            application/json:
              schema:
                type: object
                required:
                  - https_status
                  - error_code
                  - description
                  - documentation_link
                  - additional_info
                properties:
                  http_status:
                    type: integer
                    enum: [500]
                  error_code:
                    type: integer
                    description: Travel Time error code specific to parameter failing validation
                    enum: [1]
                  description:
                    type: string
                  documentation_link:
                    type: string
                    description: Url linking to Travel Time error codes documentation
                  additional_info:
                    type: object
                    description: Additional error specific information
        400:
          description: We were unable to parse the provided json body due to invalid syntax
          content:
            application/json:
              schema:
                type: object
                required:
                  - https_status
                  - error_code
                  - description
                  - documentation_link
                  - additional_info
                properties:
                  http_status:
                    type: integer
                    enum: [400]
                  error_code:
                    type: integer
                    description: Travel Time error code specific to parameter failing validation
                    enum: [3,25]
                  description:
                    type: string
                  documentation_link:
                    type: string
                    description: Url linking to Travel Time error codes documentation
                  additional_info:
                    type: object
                    description: Additional error specific information
        415:
          description: Unsupported media type
          content:
            application/json:
              schema:
                type: object
                required:
                  - https_status
                  - error_code
                  - description
                  - documentation_link
                  - additional_info
                properties:
                  http_status:
                    type: integer
                    enum: [415]
                  error_code:
                    type: integer
                    description: Travel Time error code specific to parameter failing validation
                    enum: [4]
                  description:
                    type: string
                  documentation_link:
                    type: string
                    description: Url linking to Travel Time error codes documentation
                  additional_info:
                    type: object
                    description: Additional error specific information
        422:
          description: Unprocessable Entity - Json syntax is correct, but fails validation
          content:
            application/json:
              schema:
                type: object
                required:
                  - https_status
                  - error_code
                  - description
                  - documentation_link
                  - additional_info
                properties:
                  http_status:
                    type: integer
                    enum: [422]
                  error_code:
                    type: integer
                    description: Travel Time error code specific to parameter failing validation
                    enum: [2,13,14,15,16,17,22,23,24,27]
                  description:
                    type: string
                  documentation_link:
                    type: string
                    description: Url linking to Travel Time error codes documentation
                  additional_info:
                    type: object
                    description: Details of specific parameter failing validation. May contain multiple failing parameters as key -> array
        401:
          description: Applications id or API key are missing or formatted incorrectly
          content:
            application/json:
              schema:
                type: object
                required:
                  - https_status
                  - error_code
                  - description
                  - documentation_link
                  - additional_info
                properties:
                  http_status:
                    type: integer
                    enum: [401]
                  error_code:
                    type: integer
                    description: Travel Time error code specific to parameter failing validation
                    enum: [5,6,7,8,10]
                  description:
                    type: string
                  documentation_link:
                    type: string
                    description: Url linking to Travel Time error codes documentation
                  additional_info:
                    type: object
                    description: Additional error specific information
        429:
          description: You have exceeded your request limit
          content:
            application/json:
              schema:
                type: object
                required:
                  - https_status
                  - error_code
                  - description
                  - documentation_link
                  - additional_info
                properties:
                  http_status:
                    type: integer
                    enum: [429]
                  error_code:
                    type: integer
                    description: Travel Time error code specific to parameter failing validation
                    enum: [9]
                  description:
                    type: string
                  documentation_link:
                    type: string
                    description: Url linking to Travel Time error codes documentation
                  additional_info:
                    type: object
                    description: Additional error specific information
        503:
          description: Service is temporarily unavailable, try again shortly
          content:
            application/json:
              schema:
                type: object
                required:
                  - https_status
                  - error_code
                  - description
                  - documentation_link
                  - additional_info
                properties:
                  http_status:
                    type: integer
                    enum: [503]
                  error_code:
                    type: integer
                    description: Travel Time error code specific to parameter failing validation
                    enum: [11]
                  description:
                    type: string
                  documentation_link:
                    type: string
                    description: Url linking to Travel Time error codes documentation
                  additional_info:
                    type: object
                    description: Additional error specific information
        504:
          description: Our servers have timed out while processing your request. If the problem persists, you can try splitting the current request into multiple smaller requests
          content:
            application/json:
              schema:
                type: object
                required:
                  - https_status
                  - error_code
                  - description
                  - documentation_link
                  - additional_info
                properties:
                  http_status:
                    type: integer
                    enum: [504]
                  error_code:
                    type: integer
                    description: Travel Time error code specific to parameter failing validation
                    enum: [12]
                  description:
                    type: string
                  documentation_link:
                    type: string
                    description: Url linking to Travel Time error codes documentation
                  additional_info:
                    type: object
                    description: Additional error specific information
        406:
          description: Unacceptable content type
          content:
            application/json:
              schema:
                type: object
                required:
                  - https_status
                  - error_code
                  - description
                  - documentation_link
                  - additional_info
                properties:
                  http_status:
                    type: integer
                    enum: [406]
                  error_code:
                    type: integer
                    description: Travel Time error code specific to parameter failing validation
                    enum: [19]
                  description:
                    type: string
                  documentation_link:
                    type: string
                    description: Url linking to Travel Time error codes documentation
                  additional_info:
                    type: object
                    description: Additional error specific information
        404:
          description: Requested resource is not found
          content:
            application/json:
              schema:
                type: object
                required:
                  - https_status
                  - error_code
                  - description
                  - documentation_link
                  - additional_info
                properties:
                  http_status:
                    type: integer
                    enum: [404]
                  error_code:
                    type: integer
                    description: Travel Time error code specific to parameter failing validation
                    enum: [20]
                  description:
                    type: string
                  documentation_link:
                    type: string
                    description: Url linking to Travel Time error codes documentation
                  additional_info:
                    type: object
                    description: Additional error specific information
        413:
          description: Request body is too large
          content:
            application/json:
              schema:
                type: object
                required:
                  - https_status
                  - error_code
                  - description
                  - documentation_link
                  - additional_info
                properties:
                  http_status:
                    type: integer
                    enum: [413]
                  error_code:
                    type: integer
                    description: Travel Time error code specific to parameter failing validation
                    enum: [21]
                  description:
                    type: string
                  documentation_link:
                    type: string
                    description: Url linking to Travel Time error codes documentation
                  additional_info:
                    type: object
                    description: Additional error specific information

