openapi: 3.0.0
info:
  title: Travel Time time filter fast API
  description: Json road distance API to return distance in meters from a given origin point to multiple destination points
  version: 0.0.1

paths:
  /road-distance:
    post:
      summary: Point-to-point road distance calculation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - locations
                - departure_searches
              properties:
                locations:
                  type: array
                  description: List of point locations
                  minItems: 1
                  maxItems: 2000
                  items:
                    type: object
                    required:
                      - id
                      - coords
                    properties:
                      id:
                        type: string
                        description: Unique reference to identify item in response
                      coords:
                        type: object
                        properties:
                          latitude:
                            type: number
                            description: Latitude point of origin
                          longitude:
                            type: number
                            description: Longitude point of origin
                        required:
                          - latitude
                          - longitude
                departure_searches:
                  type: array
                  description: orgin and destination configuration
                  items:
                    type: object
                    required:
                      - id
                      - departure_location_id
                      - arrival_location_ids
                      - transportation
                      - departure_time
                      - properties
                      - travel_time
                    properties:
                      id:
                        type: string
                        description: Name of request
                      departure_location_id:
                        type: string
                        description: Id from the locations array that identifies the origin location
                      arrival_location_ids:
                        type: array
                        description: Array of ids from the locations array that identify one or more destination locations
                        minItems: 1
                        maxItems: 2000
                        items:
                          type: string
                      transportation:
                        type: object
                        description: Details transportation method
                        properties:
                          type:
                            type: string
                            description: Type of transport - limited to 'driving'
                            enum: [driving]
                          parking_time:
                            type: integer
                            enum: [0]
                            description: Time in minutes to account for parking - limited to 0
                      departure_time:
                        type: string
                        pattern: /\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{6}/
                        description: Date and time string representing the departure time in extended ISO-8601 format
                      properties:
                        type: array
                        description: Data attributes to return - limited to 'distance'
                        minItems: 1
                        maxItems: 1
                        items:
                          type: string
                          enum: [distance]
                      travel_time:
                        type: integer
                        description: Maximum time in minutes to reach destinations. Locations deemed a further travel time than this are return as unreachable
              example:
                locations:
                  - id: "1001"
                    coords:
                      latitude: 50.72179229048227
                      longitude: -3.525942582444856
                  - id: "1002"
                    coords:
                      latitude: 50.72179229048227
                      longitude: -3.525942582444856
                departure_searches:
                  - id: "description of search"
                    departure_location_id: "1001"
                    arrival_location_ids:
                      - "1002"
                    transportation:
                      - type: "driving"
                        parking_time: 0
                    departure_time: "2021-05-12T08:44:35.725283"
                    properties:
                      - "distance"
                    travel_time: 7200
      responses:
        200:
          description: The request was received successfully
          content:
            application/json:
              schema:
                type: object
                required:
                  - results
                properties:
                  results:
                    type: object
                    required:
                      - search_id
                    description: Results wrapper
                    properties:
                      search_id:
                        type: string
                        description: The id specified for departure_searches in the request
                      locations:
                        type: array
                        minItems: 1
                        maxItems: 2000
                        items:
                          type: object
                          description: Details for each returned locations
                          required:
                            - id
                            - properties
                          properties:
                            id:
                              type: string
                              description: The id provided in the request for the given location
                            properties:
                              type: array
                              description: A list of any data attributes requested in departure_searches.properties
                              minItems: 1
                              maxItems: 1
                              items:
                                type: object
                                description: Requested data attributes
                                required:
                                  - distance
                                properties:
                                  distance:
                                    type: integer
                                    description: Distance from destination to this location in meters
                  unreachable:
                    type: array
                    maxItems: 2000
                    items:
                      type: string
                      description: Id of the location that has been deemed too distance to reach within travel_time

