openapi: 3.0.0
info:
  title: Travel Time time filter fast API
  description: Json road distance API to return distance in meters from a given origin point to multiple destination points
  version: 0.0.1

paths:
  /road-distance:
    post:
      summary: Point-to-point road distance calculation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - locations
                - departure_searches
              properties:
                locations:
                  type: array
                  description: List of point locations
                  minItems: 1
                  maxItems: 2000
                  items:
                    type: object
                    required:
                      - id
                      - coords
                    properties:
                      id:
                        type: string
                        description: Unique reference to identify item in response
                      coords:
                        type: object
                        properties:
                          latitude:
                            type: number
                            description: Latitude point of origin
                          longitude:
                            type: number
                            description: Longitude point of origin
                        required:
                          - latitude
                          - longitude
                departure_searches:
                  type: array
                  description: orgin and destination configuration
                  items:
                    type: object
                    required:
                      - id
                      - departure_location_id
                      - arrival_location_ids
                      - transportation
                      - departure_time
                      - properties
                      - travel_time
                    properties:
                      id:
                        type: string
                        description: Name of request
                      departure_location_id:
                        type: string
                        description: Id from the locations array that identifies the origin location
                      arrival_location_ids:
                        type: array
                        description: Array of ids from the locations array that identify one or more destination locations
                        minItems: 1
                        maxItems: 2000
                        items:
                          type: string
                      transportation:
                        type: object
                        description: Details transportation method
                        properties:
                          type:
                            type: string
                            description: Type of transport - limited to 'driving'
                            enum: [driving]
                          parking_time:
                            type: integer
                            enum: [0]
                            description: Time in minutes to account for parking - limited to 0
                          properties:
                            type: string
                            description: Data attributes to return - limited to 'distance'
                            enum: [distance]
                          travel_time:
                            type: integer
                            description: Maximum time in minutes to reach destinations. Locations deemed a further travel time than this are return as unreachable
              example:
                locations:
                  - id: "1001"
                    coords:
                      latitude: 50.72179229048227
                      longitude: -3.525942582444856
                  - id: "1002"
                    coords:
                      latitude: 50.72179229048227
                      longitude: -3.525942582444856
                departure_searches:
                  - id: "description of search"
                    departure_location_id: "1001"
                    arrival_location_ids:
                      - "1002"
                    transportation:
                      - type: "driving"
                        parking_time: 0
                    properties:
                      - "distance"
                    travel_time: 7200
      responses:
        200:
          description: The request was received successfully
