bases:
  - ../../base

patchesStrategicMerge:
  - performance-job-patch.yaml

configMapGenerator:
  - name: locust-config
    literals:
      - PERF_TEST_HOST=PERF_TEST_HOST_TO_REPLACE
      - LOCUST_HOST=PERF_TEST_HOST_TO_REPLACE
      - LOCUST_USERS=LOCUST_USERS_TO_REPLACE
      - LOCUST_SPAWN_RATE=LOCUST_SPAWN_RATE_TO_REPLACE
      - LOCUST_RUN_TIME=LOCUST_RUN_TIME_TO_REPLACE

namespace: K8S_APP_NAMESPACE_TO_REPLACE

commonLabels:
  env: ENVIRONMENT_TO_REPLACE
