apiVersion: batch/v1
kind: Job
metadata:
  namespace: K8S_APP_NAMESPACE_TO_REPLACE
  name: ${SERVICE_PREFIX_TO_REPLACE}
  labels:
    app: ${SERVICE_PREFIX_TO_REPLACE}
spec:
  template:
    metadata:
      labels:
        name: ${SERVICE_PREFIX_TO_REPLACE}
    spec:
      serviceAccountName: uec-sa
      securityContext: {}
      serviceAccount: uec-sa
      containers:
        - name: performance
          image: ${DOCKER_REGISTRY_TO_REPLACE}/performance:${BUILD_TAG_TO_REPLACE}
          envFrom:
            - configMapRef:
                name: performance-config
            - configMapRef:
                name: locust-config
          resources:
            requests:
              memory: "0Mi"
              cpu: "0m"
            limits:
              memory: "2048Mi"
              cpu: "1000m"
          imagePullPolicy: Always
      restartPolicy: Never
  backoffLimit: 0
