# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TimeFilterFastResponse.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="TimeFilterFastResponse.proto",
    package="com.igeolise.traveltime.rabbitmq.responses",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x1cTimeFilterFastResponse.proto\x12*com.igeolise.traveltime.rabbitmq.responses"\xbf\x06'
    + b"\n\x16TimeFilterFastResponse\x12W\n\x05\x65rror\x18\x01 \x01(\x0b\x32H.com.igeolise.traveltime."
    + b"rabbitmq.responses.TimeFilterFastResponse.Error\x12\x61\n\nproperties\x18\x02 \x01(\x0b\x32M.com."
    + b"igeolise.traveltime.rabbitmq.responses.TimeFilterFastResponse.Properties\x1aJ\n\nProperties\x12\x13\n"
    + b"\x0btravelTimes\x18\x01 \x03(\x11\x12\x14\n\x0cmonthlyFares\x18\x02 \x03(\x05\x12\x11\n\tdistances\x18"
    + b"\x03 \x03(\x05\x1a\x63\n\x05\x45rror\x12Z\n\x04type\x18\x01 \x01(\x0e\x32L.com.igeolise.traveltime."
    + b'rabbitmq.responses.TimeFilterFastResponse.ErrorType"\xb7\x03\n\tErrorType\x12\x0b\n\x07UNKNOWN\x10\x00'
    + b"\x12 \n\x1cONE_TO_MANY_MUST_NOT_BE_NULL\x10\x01\x12\x1b\n\x17SOURCE_MUST_NOT_BE_NULL\x10\x02\x12#\n"
    + b"\x1fTRANSPORTATION_MUST_NOT_BE_NULL\x10\x03\x12\x1a\n\x16SOURCE_NOT_IN_GEOMETRY\x10\x04\x12$"
    + b"\n UNRECOGNIZED_TRANSPORTATION_MODE\x10\x05\x12\x1d\n\x19TRAVEL_TIME_LIMIT_TOO_LOW\x10\x06\x12\x1e\n"
    + b"\x1aTRAVEL_TIME_LIMIT_TOO_HIGH\x10\x07\x12\x19\n\x15\x41UTH_ERROR_NO_USER_ID\x10\x08\x12."
    + b"\n*SERVICE_MISMATCH_WRONG_TRANSPORTATION_MODE\x10\t\x12\x17\n\x13SOURCE_OUT_OF_REACH\x10\n\x12/"
    + b"\n+INTERLEAVED_DELTAS_INVALID_COORDINATE_PAIRS\x10\x0b\x12#\n\x1f"
    + b"\x44ISTANCE_PROPERTY_NOT_SUPPORTED\x10\x0c\x62\x06proto3",
)


_TIMEFILTERFASTRESPONSE_ERRORTYPE = _descriptor.EnumDescriptor(
    name="ErrorType",
    full_name="com.igeolise.traveltime.rabbitmq.responses.TimeFilterFastResponse.ErrorType",
    filename=None,
    file=DESCRIPTOR,
    create_key=_descriptor._internal_create_key,
    values=[
        _descriptor.EnumValueDescriptor(
            name="UNKNOWN",
            index=0,
            number=0,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="ONE_TO_MANY_MUST_NOT_BE_NULL",
            index=1,
            number=1,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="SOURCE_MUST_NOT_BE_NULL",
            index=2,
            number=2,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="TRANSPORTATION_MUST_NOT_BE_NULL",
            index=3,
            number=3,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="SOURCE_NOT_IN_GEOMETRY",
            index=4,
            number=4,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="UNRECOGNIZED_TRANSPORTATION_MODE",
            index=5,
            number=5,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="TRAVEL_TIME_LIMIT_TOO_LOW",
            index=6,
            number=6,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="TRAVEL_TIME_LIMIT_TOO_HIGH",
            index=7,
            number=7,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="AUTH_ERROR_NO_USER_ID",
            index=8,
            number=8,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="SERVICE_MISMATCH_WRONG_TRANSPORTATION_MODE",
            index=9,
            number=9,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="SOURCE_OUT_OF_REACH",
            index=10,
            number=10,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="INTERLEAVED_DELTAS_INVALID_COORDINATE_PAIRS",
            index=11,
            number=11,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="DISTANCE_PROPERTY_NOT_SUPPORTED",
            index=12,
            number=12,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=469,
    serialized_end=908,
)
_sym_db.RegisterEnumDescriptor(_TIMEFILTERFASTRESPONSE_ERRORTYPE)


_TIMEFILTERFASTRESPONSE_PROPERTIES = _descriptor.Descriptor(
    name="Properties",
    full_name="com.igeolise.traveltime.rabbitmq.responses.TimeFilterFastResponse.Properties",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="travelTimes",
            full_name="com.igeolise.traveltime.rabbitmq.responses.TimeFilterFastResponse.Properties.travelTimes",
            index=0,
            number=1,
            type=17,
            cpp_type=1,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="monthlyFares",
            full_name="com.igeolise.traveltime.rabbitmq.responses.TimeFilterFastResponse.Properties.monthlyFares",
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="distances",
            full_name="com.igeolise.traveltime.rabbitmq.responses.TimeFilterFastResponse.Properties.distances",
            index=2,
            number=3,
            type=5,
            cpp_type=1,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=291,
    serialized_end=365,
)

_TIMEFILTERFASTRESPONSE_ERROR = _descriptor.Descriptor(
    name="Error",
    full_name="com.igeolise.traveltime.rabbitmq.responses.TimeFilterFastResponse.Error",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="type",
            full_name="com.igeolise.traveltime.rabbitmq.responses.TimeFilterFastResponse.Error.type",
            index=0,
            number=1,
            type=14,
            cpp_type=8,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=367,
    serialized_end=466,
)

_TIMEFILTERFASTRESPONSE = _descriptor.Descriptor(
    name="TimeFilterFastResponse",
    full_name="com.igeolise.traveltime.rabbitmq.responses.TimeFilterFastResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="error",
            full_name="com.igeolise.traveltime.rabbitmq.responses.TimeFilterFastResponse.error",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="properties",
            full_name="com.igeolise.traveltime.rabbitmq.responses.TimeFilterFastResponse.properties",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[
        _TIMEFILTERFASTRESPONSE_PROPERTIES,
        _TIMEFILTERFASTRESPONSE_ERROR,
    ],
    enum_types=[
        _TIMEFILTERFASTRESPONSE_ERRORTYPE,
    ],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=77,
    serialized_end=908,
)

_TIMEFILTERFASTRESPONSE_PROPERTIES.containing_type = _TIMEFILTERFASTRESPONSE
_TIMEFILTERFASTRESPONSE_ERROR.fields_by_name["type"].enum_type = _TIMEFILTERFASTRESPONSE_ERRORTYPE
_TIMEFILTERFASTRESPONSE_ERROR.containing_type = _TIMEFILTERFASTRESPONSE
_TIMEFILTERFASTRESPONSE.fields_by_name["error"].message_type = _TIMEFILTERFASTRESPONSE_ERROR
_TIMEFILTERFASTRESPONSE.fields_by_name["properties"].message_type = _TIMEFILTERFASTRESPONSE_PROPERTIES
_TIMEFILTERFASTRESPONSE_ERRORTYPE.containing_type = _TIMEFILTERFASTRESPONSE
DESCRIPTOR.message_types_by_name["TimeFilterFastResponse"] = _TIMEFILTERFASTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TimeFilterFastResponse = _reflection.GeneratedProtocolMessageType(
    "TimeFilterFastResponse",
    (_message.Message,),
    {
        "Properties": _reflection.GeneratedProtocolMessageType(
            "Properties",
            (_message.Message,),
            {
                "DESCRIPTOR": _TIMEFILTERFASTRESPONSE_PROPERTIES,
                "__module__": "TimeFilterFastResponse_pb2"
                # @@protoc_insertion_point(class_scope:com.igeolise.traveltime.rabbitmq.responses.TimeFilterFastResponse.Properties)
            },
        ),
        "Error": _reflection.GeneratedProtocolMessageType(
            "Error",
            (_message.Message,),
            {
                "DESCRIPTOR": _TIMEFILTERFASTRESPONSE_ERROR,
                "__module__": "TimeFilterFastResponse_pb2"
                # @@protoc_insertion_point(class_scope:com.igeolise.traveltime.rabbitmq.responses.TimeFilterFastResponse.Error)
            },
        ),
        "DESCRIPTOR": _TIMEFILTERFASTRESPONSE,
        "__module__": "TimeFilterFastResponse_pb2"
        # @@protoc_insertion_point(class_scope:com.igeolise.traveltime.rabbitmq.responses.TimeFilterFastResponse)
    },
)
_sym_db.RegisterMessage(TimeFilterFastResponse)
_sym_db.RegisterMessage(TimeFilterFastResponse.Properties)
_sym_db.RegisterMessage(TimeFilterFastResponse.Error)


# @@protoc_insertion_point(module_scope)
