name: "Check code format and quality"
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  check-code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check text files format
        run: |
          build/automation/etc/githooks/scripts/editorconfig-pre-commit.sh
      - name: Check Python files format
        run: |
          build/automation/etc/githooks/scripts/python-code-pre-commit.sh
      - name: Check Terraform files format
        run: |
          build/automation/etc/githooks/scripts/terraform-format-pre-commit.sh
      - name: Create coverage report
        run: |
          make build-tester coverage PROFILE=local
      - uses: SonarSource/sonarqube-scan-action@v5.3.0
        # SEE: https://github.com/SonarSource/sonarcloud-github-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.RD_SONAR_TOKEN }}
        with:
          projectBaseDir: ./application/roaddistance
          args: >
            -Dsonar.organization=nhsd-exeter
            -Dsonar.projectKey=uec-dos-rd
            -Dsonar.coverage.exclusions=tests/****/*,utilities/*
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.python.version=3.13
