resources:
  - namespace.yaml
  - network-policy/default-deny-ingress.yaml
  - performance-job.yaml
  - performance-sa.yaml

configMapGenerator:
  - name: performance-config
    literals:
      - PROFILE=PROFILE_TO_REPLACE
      - ENVIRONMENT=ENVIRONMENT_TO_REPLACE
      - API_ENDPOINT=API_ENDPOINT_TO_REPLACE
      - API_RD_TOKEN=API_RD_TOKEN_TO_REPLACE
      - SERVICE_PREFIX=SERVICE_PREFIX_TO_REPLACE
      - LOCUST_LOCUSTFILE=LOCUST_LOCUSTFILE_TO_REPLACE
      - LOCUST_TAGS=LOCUST_TAGS_TO_REPLACE
      - LOCUST_USERS=LOCUST_USERS_TO_REPLACE
      - LOCUST_SPAWN_RATE=LOCUST_SPAWN_RATE_TO_REPLACE
      - LOCUST_RUN_TIME=LOCUST_RUN_TIME_TO_REPLACE

namespace: K8S_APP_NAMESPACE_TO_REPLACE

commonLabels:
  env: ENVIRONMENT_TO_REPLACE
