resources:
  - namespace.yaml
  - network-policy/default-deny-ingress.yaml
  - performance-job.yaml
  - performance-sa.yaml

configMapGenerator:
  - name: performance-config
    literals:
      - PROFILE=PROFILE_TO_REPLACE
      - ENVIRONMENT=ENVIRONMENT_TO_REPLACE
      - API_ENDPOINT=API_ENDPOINT_TO_REPLACE
      - PERF_TEST_HOST=PERF_TEST_HOST_TO_REPLACE
      - SERVICE_PREFIX=SERVICE_PREFIX_TO_REPLACE
      - LOCUST_LOCUSTFILE=LOCUST_LOCUSTFILE_TO_REPLACE

namespace: K8S_APP_NAMESPACE_TO_REPLACE

labels:
  - pairs:
      env: ENVIRONMENT_TO_REPLACE
